// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoConfig.proto

package eagle.network;

public final class EagleProtoBuf {
  private EagleProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eagle.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>repeated string requestStrings = 5;</code>
     */
    com.google.protobuf.ProtocolStringList
        getRequestStringsList();
    /**
     * <code>repeated string requestStrings = 5;</code>
     */
    int getRequestStringsCount();
    /**
     * <code>repeated string requestStrings = 5;</code>
     */
    java.lang.String getRequestStrings(int index);
    /**
     * <code>repeated string requestStrings = 5;</code>
     */
    com.google.protobuf.ByteString
        getRequestStringsBytes(int index);
  }
  /**
   * Protobuf type {@code eagle.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eagle.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                requestStrings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              requestStrings_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          requestStrings_ = requestStrings_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eagle.network.EagleProtoBuf.internal_static_eagle_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eagle.network.EagleProtoBuf.internal_static_eagle_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eagle.network.EagleProtoBuf.Request.class, eagle.network.EagleProtoBuf.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int REQUESTSTRINGS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList requestStrings_;
    /**
     * <code>repeated string requestStrings = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRequestStringsList() {
      return requestStrings_;
    }
    /**
     * <code>repeated string requestStrings = 5;</code>
     */
    public int getRequestStringsCount() {
      return requestStrings_.size();
    }
    /**
     * <code>repeated string requestStrings = 5;</code>
     */
    public java.lang.String getRequestStrings(int index) {
      return requestStrings_.get(index);
    }
    /**
     * <code>repeated string requestStrings = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRequestStringsBytes(int index) {
      return requestStrings_.getByteString(index);
    }

    private void initFields() {
      id_ = 0;
      requestStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      for (int i = 0; i < requestStrings_.size(); i++) {
        output.writeBytes(5, requestStrings_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < requestStrings_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(requestStrings_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getRequestStringsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eagle.network.EagleProtoBuf.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eagle.network.EagleProtoBuf.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eagle.network.EagleProtoBuf.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eagle.network.EagleProtoBuf.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eagle.network.EagleProtoBuf.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eagle.network.EagleProtoBuf.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eagle.network.EagleProtoBuf.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eagle.network.EagleProtoBuf.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eagle.network.EagleProtoBuf.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eagle.network.EagleProtoBuf.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eagle.network.EagleProtoBuf.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eagle.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eagle.Request)
        eagle.network.EagleProtoBuf.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eagle.network.EagleProtoBuf.internal_static_eagle_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eagle.network.EagleProtoBuf.internal_static_eagle_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eagle.network.EagleProtoBuf.Request.class, eagle.network.EagleProtoBuf.Request.Builder.class);
      }

      // Construct using eagle.network.EagleProtoBuf.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        requestStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eagle.network.EagleProtoBuf.internal_static_eagle_Request_descriptor;
      }

      public eagle.network.EagleProtoBuf.Request getDefaultInstanceForType() {
        return eagle.network.EagleProtoBuf.Request.getDefaultInstance();
      }

      public eagle.network.EagleProtoBuf.Request build() {
        eagle.network.EagleProtoBuf.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eagle.network.EagleProtoBuf.Request buildPartial() {
        eagle.network.EagleProtoBuf.Request result = new eagle.network.EagleProtoBuf.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          requestStrings_ = requestStrings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.requestStrings_ = requestStrings_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eagle.network.EagleProtoBuf.Request) {
          return mergeFrom((eagle.network.EagleProtoBuf.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eagle.network.EagleProtoBuf.Request other) {
        if (other == eagle.network.EagleProtoBuf.Request.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.requestStrings_.isEmpty()) {
          if (requestStrings_.isEmpty()) {
            requestStrings_ = other.requestStrings_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRequestStringsIsMutable();
            requestStrings_.addAll(other.requestStrings_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eagle.network.EagleProtoBuf.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eagle.network.EagleProtoBuf.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList requestStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRequestStringsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          requestStrings_ = new com.google.protobuf.LazyStringArrayList(requestStrings_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRequestStringsList() {
        return requestStrings_.getUnmodifiableView();
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public int getRequestStringsCount() {
        return requestStrings_.size();
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public java.lang.String getRequestStrings(int index) {
        return requestStrings_.get(index);
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRequestStringsBytes(int index) {
        return requestStrings_.getByteString(index);
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public Builder setRequestStrings(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRequestStringsIsMutable();
        requestStrings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public Builder addRequestStrings(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRequestStringsIsMutable();
        requestStrings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public Builder addAllRequestStrings(
          java.lang.Iterable<java.lang.String> values) {
        ensureRequestStringsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, requestStrings_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public Builder clearRequestStrings() {
        requestStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string requestStrings = 5;</code>
       */
      public Builder addRequestStringsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRequestStringsIsMutable();
        requestStrings_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eagle.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eagle.Request)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eagle.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required .eagle.Response.ResponseType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .eagle.Response.ResponseType type = 2;</code>
     */
    eagle.network.EagleProtoBuf.Response.ResponseType getType();

    /**
     * <code>repeated string responseStrings = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getResponseStringsList();
    /**
     * <code>repeated string responseStrings = 3;</code>
     */
    int getResponseStringsCount();
    /**
     * <code>repeated string responseStrings = 3;</code>
     */
    java.lang.String getResponseStrings(int index);
    /**
     * <code>repeated string responseStrings = 3;</code>
     */
    com.google.protobuf.ByteString
        getResponseStringsBytes(int index);
  }
  /**
   * Protobuf type {@code eagle.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eagle.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              eagle.network.EagleProtoBuf.Response.ResponseType value = eagle.network.EagleProtoBuf.Response.ResponseType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                responseStrings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              responseStrings_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          responseStrings_ = responseStrings_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eagle.network.EagleProtoBuf.internal_static_eagle_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eagle.network.EagleProtoBuf.internal_static_eagle_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eagle.network.EagleProtoBuf.Response.class, eagle.network.EagleProtoBuf.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code eagle.Response.ResponseType}
     */
    public enum ResponseType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOG = 0;</code>
       */
      LOG(0, 0),
      /**
       * <code>COMMAND = 1;</code>
       */
      COMMAND(1, 1),
      /**
       * <code>OTHER = 2;</code>
       */
      OTHER(2, 2),
      ;

      /**
       * <code>LOG = 0;</code>
       */
      public static final int LOG_VALUE = 0;
      /**
       * <code>COMMAND = 1;</code>
       */
      public static final int COMMAND_VALUE = 1;
      /**
       * <code>OTHER = 2;</code>
       */
      public static final int OTHER_VALUE = 2;


      public final int getNumber() { return value; }

      public static ResponseType valueOf(int value) {
        switch (value) {
          case 0: return LOG;
          case 1: return COMMAND;
          case 2: return OTHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
              public ResponseType findValueByNumber(int number) {
                return ResponseType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return eagle.network.EagleProtoBuf.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResponseType[] VALUES = values();

      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResponseType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:eagle.Response.ResponseType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private eagle.network.EagleProtoBuf.Response.ResponseType type_;
    /**
     * <code>required .eagle.Response.ResponseType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .eagle.Response.ResponseType type = 2;</code>
     */
    public eagle.network.EagleProtoBuf.Response.ResponseType getType() {
      return type_;
    }

    public static final int RESPONSESTRINGS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList responseStrings_;
    /**
     * <code>repeated string responseStrings = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getResponseStringsList() {
      return responseStrings_;
    }
    /**
     * <code>repeated string responseStrings = 3;</code>
     */
    public int getResponseStringsCount() {
      return responseStrings_.size();
    }
    /**
     * <code>repeated string responseStrings = 3;</code>
     */
    public java.lang.String getResponseStrings(int index) {
      return responseStrings_.get(index);
    }
    /**
     * <code>repeated string responseStrings = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResponseStringsBytes(int index) {
      return responseStrings_.getByteString(index);
    }

    private void initFields() {
      id_ = 0;
      type_ = eagle.network.EagleProtoBuf.Response.ResponseType.LOG;
      responseStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      for (int i = 0; i < responseStrings_.size(); i++) {
        output.writeBytes(3, responseStrings_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < responseStrings_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(responseStrings_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getResponseStringsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eagle.network.EagleProtoBuf.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eagle.network.EagleProtoBuf.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eagle.network.EagleProtoBuf.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eagle.network.EagleProtoBuf.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eagle.network.EagleProtoBuf.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eagle.network.EagleProtoBuf.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eagle.network.EagleProtoBuf.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eagle.network.EagleProtoBuf.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eagle.network.EagleProtoBuf.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eagle.network.EagleProtoBuf.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eagle.network.EagleProtoBuf.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eagle.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eagle.Response)
        eagle.network.EagleProtoBuf.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eagle.network.EagleProtoBuf.internal_static_eagle_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eagle.network.EagleProtoBuf.internal_static_eagle_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eagle.network.EagleProtoBuf.Response.class, eagle.network.EagleProtoBuf.Response.Builder.class);
      }

      // Construct using eagle.network.EagleProtoBuf.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = eagle.network.EagleProtoBuf.Response.ResponseType.LOG;
        bitField0_ = (bitField0_ & ~0x00000002);
        responseStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eagle.network.EagleProtoBuf.internal_static_eagle_Response_descriptor;
      }

      public eagle.network.EagleProtoBuf.Response getDefaultInstanceForType() {
        return eagle.network.EagleProtoBuf.Response.getDefaultInstance();
      }

      public eagle.network.EagleProtoBuf.Response build() {
        eagle.network.EagleProtoBuf.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eagle.network.EagleProtoBuf.Response buildPartial() {
        eagle.network.EagleProtoBuf.Response result = new eagle.network.EagleProtoBuf.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          responseStrings_ = responseStrings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.responseStrings_ = responseStrings_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eagle.network.EagleProtoBuf.Response) {
          return mergeFrom((eagle.network.EagleProtoBuf.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eagle.network.EagleProtoBuf.Response other) {
        if (other == eagle.network.EagleProtoBuf.Response.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.responseStrings_.isEmpty()) {
          if (responseStrings_.isEmpty()) {
            responseStrings_ = other.responseStrings_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureResponseStringsIsMutable();
            responseStrings_.addAll(other.responseStrings_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eagle.network.EagleProtoBuf.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eagle.network.EagleProtoBuf.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private eagle.network.EagleProtoBuf.Response.ResponseType type_ = eagle.network.EagleProtoBuf.Response.ResponseType.LOG;
      /**
       * <code>required .eagle.Response.ResponseType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .eagle.Response.ResponseType type = 2;</code>
       */
      public eagle.network.EagleProtoBuf.Response.ResponseType getType() {
        return type_;
      }
      /**
       * <code>required .eagle.Response.ResponseType type = 2;</code>
       */
      public Builder setType(eagle.network.EagleProtoBuf.Response.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .eagle.Response.ResponseType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = eagle.network.EagleProtoBuf.Response.ResponseType.LOG;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList responseStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureResponseStringsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          responseStrings_ = new com.google.protobuf.LazyStringArrayList(responseStrings_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getResponseStringsList() {
        return responseStrings_.getUnmodifiableView();
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public int getResponseStringsCount() {
        return responseStrings_.size();
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public java.lang.String getResponseStrings(int index) {
        return responseStrings_.get(index);
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResponseStringsBytes(int index) {
        return responseStrings_.getByteString(index);
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public Builder setResponseStrings(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResponseStringsIsMutable();
        responseStrings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public Builder addResponseStrings(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResponseStringsIsMutable();
        responseStrings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public Builder addAllResponseStrings(
          java.lang.Iterable<java.lang.String> values) {
        ensureResponseStringsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, responseStrings_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public Builder clearResponseStrings() {
        responseStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string responseStrings = 3;</code>
       */
      public Builder addResponseStringsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResponseStringsIsMutable();
        responseStrings_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eagle.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eagle.Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eagle_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eagle_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eagle_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eagle_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ProtoConfig.proto\022\005eagle\"-\n\007Request\022\n\n" +
      "\002id\030\001 \002(\r\022\026\n\016requestStrings\030\005 \003(\t\"\214\001\n\010Re" +
      "sponse\022\n\n\002id\030\001 \002(\r\022*\n\004type\030\002 \002(\0162\034.eagle" +
      ".Response.ResponseType\022\027\n\017responseString" +
      "s\030\003 \003(\t\"/\n\014ResponseType\022\007\n\003LOG\020\000\022\013\n\007COMM" +
      "AND\020\001\022\t\n\005OTHER\020\002B\036\n\reagle.networkB\rEagle" +
      "ProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eagle_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eagle_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eagle_Request_descriptor,
        new java.lang.String[] { "Id", "RequestStrings", });
    internal_static_eagle_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eagle_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eagle_Response_descriptor,
        new java.lang.String[] { "Id", "Type", "ResponseStrings", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
